Repository eveseat/services, pull requests merged in 2020-05, with the labels that each got.

#131 revert: rollback abstract provider change
  src/AbstractSeatPlugin.php
  src/ServicesServiceProvider.php
Labels: fix

#133 refactor(moons): simplify relationships
  src/Repositories/Corporation/Extractions.php
Labels: refactor

#134 feat(sde): explode map into specific entities
  src/Repositories/Character/MiningLedger.php
  src/Repositories/Corporation/Extractions.php
  src/Repositories/Corporation/Structures.php
Labels: refactor

#135 fix(sso): ensure scopes are properly handled - even if single
  src/Socialite/EveOnline/Checker/Claim/ScpChecker.php
  src/Socialite/EveOnline/Provider.php
Labels: fix

#129 enhance sso: ability to define scope profiles
  src/Socialite/EveOnline/Provider.php
  src/database/migrations/2020_04_27_231132_convert_sso_scopes_to_list.php
Labels: enhancement

#136 fix: add missing publicData scope
  src/Settings/Seat.php
Labels: fix

#137 fix(sso): ensure default settings are handled like json
  src/Settings/Seat.php
  src/Settings/Settings.php
  src/database/migrations/2020_04_27_231132_convert_sso_scopes_to_list.php
Labels: fix
